"""Add ExamShield models

Revision ID: 0a180f8dbc1b
Revises: 99433a4f3033
Create Date: 2026-08-20 10:39:57.773718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a180f8dbc1b'
down_revision: Union[str, Sequence[str], None] = '99433a4f3033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_integrity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('RIGHT_CLICK_ATTEMPT', 'COPY_ATTEMPT', 'CUT_ATTEMPT', 'PASTE_ATTEMPT', 'PRINT_ATTEMPT', 'DEVTOOLS_ATTEMPT', 'TAB_SWITCH', 'TAB_RETURN', 'FOCUS_LOST', 'FOCUS_REGAINED', 'FULLSCREEN_EXIT', 'FULLSCREEN_ENTER', 'KEYBOARD_VIOLATION', 'DRAG_ATTEMPT', 'EXTERNAL_DROP_ATTEMPT', 'NAVIGATION_ATTEMPT', name='examintegrityeventtype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_integrity_events_attempt_id'), 'exam_integrity_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_integrity_events_id'), 'exam_integrity_events', ['id'], unique=False)
    op.add_column('quizzes', sa.Column('is_secure_mode', sa.Boolean(), nullable=True))
    op.add_column('quizzes', sa.Column('secure_mode_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'secure_mode_config')
    op.drop_column('quizzes', 'is_secure_mode')
    op.drop_index(op.f('ix_exam_integrity_events_id'), table_name='exam_integrity_events')
    op.drop_index(op.f('ix_exam_integrity_events_attempt_id'), table_name='exam_integrity_events')
    op.drop_table('exam_integrity_events')
    # ### end Alembic commands ###
