"""Add innovation features

Revision ID: 99433a4f3033
Revises: fda2c0c5a255
Create Date: 2026-08-19 21:26:22.837478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99433a4f3033'
down_revision: Union[str, Sequence[str], None] = 'fda2c0c5a255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('answer_changes', sa.Integer(), nullable=True))
    op.add_column('options', sa.Column('story_consequence', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('story_context', sa.Text(), nullable=True))
    op.add_column('quizzes', sa.Column('is_story_mode', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('uq_quizzes_join_code'), 'quizzes', type_='unique')
    op.create_index(op.f('ix_quizzes_join_code'), 'quizzes', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_join_code'), table_name='quizzes')
    op.create_unique_constraint(op.f('uq_quizzes_join_code'), 'quizzes', ['join_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('quizzes', 'is_story_mode')
    op.drop_column('questions', 'story_context')
    op.drop_column('options', 'story_consequence')
    op.drop_column('answers', 'answer_changes')
    op.drop_column('answers', 'time_spent_seconds')
    # ### end Alembic commands ###
